CREATE TABLE [dbo].[Trip]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TransactionNo] VARCHAR(100) NOT NULL UNIQUE,
    [CompanyId] INT NOT NULL,
    [TransactionDateTime] DATETIME NOT NULL,
    [FinancialYearId] INT NOT NULL,
    [ChallanNo] VARCHAR(MAX) NULL,
    [OMCId] INT NOT NULL,
    [VehicleId] INT NOT NULL,
    [DriverId] INT NOT NULL,
    [RouteId] INT NOT NULL,
    [Quantity] MONEY NOT NULL,
    [TotalExpense] MONEY NOT NULL,
    [VehicleEmpty] BIT NOT NULL DEFAULT 0,
    [BillId] INT NULL,
    [GrossAmount] MONEY NULL,
    [TDSAmount] MONEY NULL,
    [PenaltyAmount] MONEY NULL,
    [NetAmount] MONEY NULL,
    [Remarks] VARCHAR(MAX) NULL,
	[CreatedBy] INT NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT (((getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'India Standard Time')),
	[CreatedFromPlatform] VARCHAR(MAX) NOT NULL,
	[Status] BIT NOT NULL DEFAULT 1,
	[LastModifiedBy] INT NULL,
	[LastModifiedAt] DATETIME NULL, 
	[LastModifiedFromPlatform] VARCHAR(MAX) NULL, 
	CONSTRAINT [FK_Trip_ToCompany] FOREIGN KEY ([CompanyId]) REFERENCES [Company]([Id]),
    CONSTRAINT [FK_Trip_ToFinancialYear] FOREIGN KEY ([FinancialYearId]) REFERENCES [FinancialYear](Id), 
    CONSTRAINT [FK_Trip_ToOMC] FOREIGN KEY ([OMCId]) REFERENCES [OMC]([Id]),
    CONSTRAINT [FK_Trip_ToVehicle] FOREIGN KEY ([VehicleId]) REFERENCES [Vehicle]([Id]),
    CONSTRAINT [FK_Trip_ToDriver] FOREIGN KEY ([DriverId]) REFERENCES [Driver]([Id]),
    CONSTRAINT [FK_Trip_ToRoute] FOREIGN KEY ([RouteId]) REFERENCES [Route]([Id]),
    CONSTRAINT [FK_Trip_ToBill] FOREIGN KEY ([BillId]) REFERENCES [Bill]([Id]),
    CONSTRAINT [FK_Trip_CreatedBy_ToUser] FOREIGN KEY ([CreatedBy]) REFERENCES [User]([Id]),
	CONSTRAINT [FK_Trip_LastModifiedBy_ToUser] FOREIGN KEY ([LastModifiedBy]) REFERENCES [User]([Id])
)
