CREATE TABLE [dbo].[Bill]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TransactionNo] VARCHAR(100) NOT NULL UNIQUE,
    [CompanyId] INT NOT NULL,
    [TransactionDateTime] DATETIME NOT NULL,
    [FinancialYearId] INT NOT NULL,
    [BillNo] VARCHAR(MAX) NOT NULL,
    [OMCId] INT NOT NULL,
    [TotalGrossAmount] MONEY NOT NULL,
    [TotalPenaltyAmount] MONEY NOT NULL,
    [TotalNetAmount] MONEY NOT NULL,
    [TotalLedgerPaymentAmount] MONEY NOT NULL,
    [Remarks] VARCHAR(MAX) NULL,
	[FinancialAccountingId] INT NULL,
	[CreatedBy] INT NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT (((getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'India Standard Time')),
	[CreatedFromPlatform] VARCHAR(MAX) NOT NULL,
	[Status] BIT NOT NULL DEFAULT 1,
	[LastModifiedBy] INT NULL,
	[LastModifiedAt] DATETIME NULL, 
	[LastModifiedFromPlatform] VARCHAR(MAX) NULL, 
    CONSTRAINT [FK_Bill_ToCompany] FOREIGN KEY ([CompanyId]) REFERENCES [Company]([Id]),
    CONSTRAINT [FK_Bill_ToFinancialYear] FOREIGN KEY ([FinancialYearId]) REFERENCES [FinancialYear](Id), 
    CONSTRAINT [FK_Bill_ToOMC] FOREIGN KEY ([OMCId]) REFERENCES [OMC]([Id]),
    CONSTRAINT [FK_Bill_ToFinancialAccounting] FOREIGN KEY ([FinancialAccountingId]) REFERENCES [FinancialAccounting]([Id]),
    CONSTRAINT [FK_Bill_CreatedBy_ToUser] FOREIGN KEY ([CreatedBy]) REFERENCES [User]([Id]),
	CONSTRAINT [FK_Bill_LastModifiedBy_ToUser] FOREIGN KEY ([LastModifiedBy]) REFERENCES [User]([Id])
)
