CREATE TABLE [dbo].[OMCCard]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [CardNumber] VARCHAR(250) NOT NULL UNIQUE,
    [Code] VARCHAR(10) NOT NULL UNIQUE, 
    [OMCId] INT NOT NULL,
    [OpeningBalance] MONEY NOT NULL,
    [Remarks] VARCHAR(MAX) NULL,
    [Status] BIT NOT NULL DEFAULT 1,
    CONSTRAINT [FK_OMCCard_ToOMC] FOREIGN KEY ([OMCId]) REFERENCES [OMC]([Id])
)
