CREATE TABLE [dbo].[VehicleTrip]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TransactionNo] VARCHAR(100) NOT NULL UNIQUE,
    [CompanyId] INT NOT NULL,
    [TransactionDateTime] DATETIME NOT NULL,
    [FinancialYearId] INT NOT NULL,
    [ChallanNo] VARCHAR(MAX) NOT NULL,
    [ChallanDateTime] DATETIME NOT NULL,
    [OMCId] INT NOT NULL,
    [VehicleId] INT NOT NULL,
    [DriverId] INT NOT NULL,
    [RouteId] INT NOT NULL,
    [Quantity] MONEY NOT NULL,
    [Remarks] VARCHAR(MAX) NULL,
	[CreatedBy] INT NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT (((getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'India Standard Time')),
	[CreatedFromPlatform] VARCHAR(MAX) NOT NULL,
	[Status] BIT NOT NULL DEFAULT 1,
	[LastModifiedBy] INT NULL,
	[LastModifiedAt] DATETIME NULL, 
	[LastModifiedFromPlatform] VARCHAR(MAX) NULL, 
	CONSTRAINT [FK_VehicleTrip_ToCompany] FOREIGN KEY ([CompanyId]) REFERENCES [Company]([Id]),
    CONSTRAINT [FK_VehicleTrip_ToFinancialYear] FOREIGN KEY ([FinancialYearId]) REFERENCES [FinancialYear](Id), 
    CONSTRAINT [FK_VehicleTrip_ToOMC] FOREIGN KEY ([OMCId]) REFERENCES [OMC]([Id]),
    CONSTRAINT [FK_VehicleTrip_ToVehicle] FOREIGN KEY ([VehicleId]) REFERENCES [Vehicle]([Id]),
    CONSTRAINT [FK_VehicleTrip_ToDriver] FOREIGN KEY ([DriverId]) REFERENCES [VehicleDriver]([Id]),
    CONSTRAINT [FK_VehicleTrip_ToRoute] FOREIGN KEY ([RouteId]) REFERENCES [VehicleRoute]([Id]),
    CONSTRAINT [FK_VehicleTrip_CreatedBy_ToUser] FOREIGN KEY ([CreatedBy]) REFERENCES [User]([Id]),
	CONSTRAINT [FK_VehicleTrip_LastModifiedBy_ToUser] FOREIGN KEY ([LastModifiedBy]) REFERENCES [User]([Id])
)
